# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/AXI/AXI_Lite/ownAXIL/vproj_axi_lite/vproj_axi_lite.srcs/sources_1/ip/axi_vip_0/axi_vip_0.xci
# IP: The module: 'axi_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/AXI/AXI_Lite/ownAXIL/vproj_axi_lite/vproj_axi_lite.srcs/sources_1/ip/axi_vip_0/axi_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vip_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Documents/AXI/AXI_Lite/ownAXIL/vproj_axi_lite/vproj_axi_lite.srcs/sources_1/ip/axi_vip_0/axi_vip_0.xci
# IP: The module: 'axi_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/AXI/AXI_Lite/ownAXIL/vproj_axi_lite/vproj_axi_lite.srcs/sources_1/ip/axi_vip_0/axi_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
